platform :ios, '9.0'

target 'PersonalLibrary' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PersonalLibrary
pod 'RealmSwift'
pod 'SwipeCellKit'

end
